version: "3"
services:
  #Servidor PHP
  php:
    build: ./docker/php
    container_name: php
    volumes:
      - ./app:/var/www/html
    links:
      - db
    networks:
      - project-network
  #Servidor Web APACHE
  web:
    build: ./docker/apache
    container_name: apache
    volumes:
      - ./app:/var/www/html
    ports:
      - "80:80"
    links:
      - php
    networks:
      - project-network
  #Servidor Banco de Dados Maria DB
  db:
    image: mariadb
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: elephpant
      #      MYSQL_USER: root
      MYSQL_PASSWORD: usuario37
      MYSQL_ROOT_PASSWORD: usuario37
    volumes:
      - ./docker/database:/var/lib/mysql
    networks:
      - project-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    links:
      - db
    ports:
      - 8181:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: usuario37
      PMA_ARBITRARY: 1
    networks:
      - project-network
networks:
  project-network:
    driver: bridge
