version: "3"
services:
  #Servidor PHP
  php:
    build: ./docker/php
    container_name: php
    volumes:
      - ./app:/var/www/html
    links:
      - db
    networks:
      - divbr-network
  #Servidor Web APACHE
  web:
    build: ./docker/apache
    container_name: apache
    volumes:
      - ./app:/var/www/html
    ports:
      - "8000:80" #Porta a ser acessada via Localhost
    links:
      - php
    networks:
      - divbr-network
  #Servidor Banco de Dados Maria DB
  db:
    image: mysql
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: divbr
      MYSQL_USER: divbr
      MYSQL_PASSWORD: divbr
      MYSQL_ROOT_PASSWORD: divbr
    volumes:
      - ./docker/database:/var/lib/mysql
    networks:
      - divbr-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    links:
      - db
    ports:
      - 8181:80
    environment:
      MYSQL_USERNAME: divbr
      MYSQL_ROOT_PASSWORD: divbr
      PMA_ARBITRARY: 1
    networks:
      - divbr-network
networks:
  divbr-network:
    driver: bridge